/*
 * generated by Xtext 2.22.0
 */
package symboleoci.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import symboleoci.ide.contentassist.antlr.internal.InternalSymboleociParser;
import symboleoci.services.SymboleociGrammarAccess;

public class SymboleociParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SymboleociGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SymboleociGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDConceptAccess().getAlternatives(), "rule__DConcept__Alternatives");
			builder.put(grammarAccess.getCTypeAccess().getAlternatives(), "rule__CType__Alternatives");
			builder.put(grammarAccess.getBasicTypeAccess().getAlternatives(), "rule__BasicType__Alternatives");
			builder.put(grammarAccess.getOntoCTypeAccess().getAlternatives(), "rule__OntoCType__Alternatives");
			builder.put(grammarAccess.getTypeNameAccess().getAlternatives(), "rule__TypeName__Alternatives");
			builder.put(grammarAccess.getAtomAccess().getAlternatives(), "rule__Atom__Alternatives");
			builder.put(grammarAccess.getSitPropAccess().getAlternatives(), "rule__SitProp__Alternatives");
			builder.put(grammarAccess.getEventPropAccess().getAlternatives(), "rule__EventProp__Alternatives");
			builder.put(grammarAccess.getIntervalAccess().getAlternatives(), "rule__Interval__Alternatives");
			builder.put(grammarAccess.getSitNameAccess().getAlternatives(), "rule__SitName__Alternatives");
			builder.put(grammarAccess.getUnitAccess().getAlternatives(), "rule__Unit__Alternatives");
			builder.put(grammarAccess.getTempOpAccess().getAlternatives(), "rule__TempOp__Alternatives");
			builder.put(grammarAccess.getPointAccess().getAlternatives(), "rule__Point__Alternatives");
			builder.put(grammarAccess.getPowEventAccess().getAlternatives(), "rule__PowEvent__Alternatives");
			builder.put(grammarAccess.getContrEventAccess().getAlternatives(), "rule__ContrEvent__Alternatives");
			builder.put(grammarAccess.getOblEventAccess().getAlternatives(), "rule__OblEvent__Alternatives");
			builder.put(grammarAccess.getOblStateAccess().getAlternatives(), "rule__OblState__Alternatives");
			builder.put(grammarAccess.getContrStateAccess().getAlternatives(), "rule__ContrState__Alternatives");
			builder.put(grammarAccess.getPowStateAccess().getAlternatives(), "rule__PowState__Alternatives");
			builder.put(grammarAccess.getSetExpAccess().getAlternatives(), "rule__SetExp__Alternatives");
			builder.put(grammarAccess.getContractSpecAccess().getGroup(), "rule__ContractSpec__Group__0");
			builder.put(grammarAccess.getDomainSpecAccess().getGroup(), "rule__DomainSpec__Group__0");
			builder.put(grammarAccess.getDomainSpecAccess().getGroup_2(), "rule__DomainSpec__Group_2__0");
			builder.put(grammarAccess.getDConceptAccess().getGroup_0(), "rule__DConcept__Group_0__0");
			builder.put(grammarAccess.getDConceptAccess().getGroup_0_1(), "rule__DConcept__Group_0_1__0");
			builder.put(grammarAccess.getDConceptAccess().getGroup_0_3(), "rule__DConcept__Group_0_3__0");
			builder.put(grammarAccess.getDConceptAccess().getGroup_1(), "rule__DConcept__Group_1__0");
			builder.put(grammarAccess.getDConceptAccess().getGroup_1_4(), "rule__DConcept__Group_1_4__0");
			builder.put(grammarAccess.getEnumItemAccess().getGroup(), "rule__EnumItem__Group__0");
			builder.put(grammarAccess.getCTypeAccess().getGroup_1(), "rule__CType__Group_1__0");
			builder.put(grammarAccess.getCTypeAccess().getGroup_2(), "rule__CType__Group_2__0");
			builder.put(grammarAccess.getContractAccess().getGroup(), "rule__Contract__Group__0");
			builder.put(grammarAccess.getContractAccess().getGroup_3(), "rule__Contract__Group_3__0");
			builder.put(grammarAccess.getContractAccess().getGroup_6(), "rule__Contract__Group_6__0");
			builder.put(grammarAccess.getContractAccess().getGroup_6_1(), "rule__Contract__Group_6_1__0");
			builder.put(grammarAccess.getContractAccess().getGroup_7(), "rule__Contract__Group_7__0");
			builder.put(grammarAccess.getContractAccess().getGroup_7_1(), "rule__Contract__Group_7_1__0");
			builder.put(grammarAccess.getContractAccess().getGroup_8(), "rule__Contract__Group_8__0");
			builder.put(grammarAccess.getContractAccess().getGroup_8_1(), "rule__Contract__Group_8_1__0");
			builder.put(grammarAccess.getContractAccess().getGroup_10(), "rule__Contract__Group_10__0");
			builder.put(grammarAccess.getContractAccess().getGroup_11(), "rule__Contract__Group_11__0");
			builder.put(grammarAccess.getContractAccess().getGroup_11_1(), "rule__Contract__Group_11_1__0");
			builder.put(grammarAccess.getContractAccess().getGroup_12(), "rule__Contract__Group_12__0");
			builder.put(grammarAccess.getContractAccess().getGroup_12_1(), "rule__Contract__Group_12_1__0");
			builder.put(grammarAccess.getContractAccess().getGroup_13(), "rule__Contract__Group_13__0");
			builder.put(grammarAccess.getContractAccess().getGroup_13_1(), "rule__Contract__Group_13_1__0");
			builder.put(grammarAccess.getDeclarAccess().getGroup(), "rule__Declar__Group__0");
			builder.put(grammarAccess.getDeclarAccess().getGroup_2(), "rule__Declar__Group_2__0");
			builder.put(grammarAccess.getDeclarAccess().getGroup_3(), "rule__Declar__Group_3__0");
			builder.put(grammarAccess.getDeclarPairAccess().getGroup(), "rule__DeclarPair__Group__0");
			builder.put(grammarAccess.getPairAccess().getGroup(), "rule__Pair__Group__0");
			builder.put(grammarAccess.getTypeNameAccess().getGroup_1(), "rule__TypeName__Group_1__0");
			builder.put(grammarAccess.getOblAccess().getGroup(), "rule__Obl__Group__0");
			builder.put(grammarAccess.getOblAccess().getGroup_2(), "rule__Obl__Group_2__0");
			builder.put(grammarAccess.getPropAccess().getGroup(), "rule__Prop__Group__0");
			builder.put(grammarAccess.getPropAccess().getGroup_1(), "rule__Prop__Group_1__0");
			builder.put(grammarAccess.getJuncAccess().getGroup(), "rule__Junc__Group__0");
			builder.put(grammarAccess.getJuncAccess().getGroup_1(), "rule__Junc__Group_1__0");
			builder.put(grammarAccess.getNegAccess().getGroup(), "rule__Neg__Group__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_2(), "rule__Atom__Group_2__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_2_2(), "rule__Atom__Group_2_2__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_2_4(), "rule__Atom__Group_2_4__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_2_5(), "rule__Atom__Group_2_5__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_3(), "rule__Atom__Group_3__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_4(), "rule__Atom__Group_4__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_5(), "rule__Atom__Group_5__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_6(), "rule__Atom__Group_6__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_7(), "rule__Atom__Group_7__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_8(), "rule__Atom__Group_8__0");
			builder.put(grammarAccess.getSitPropAccess().getGroup_0(), "rule__SitProp__Group_0__0");
			builder.put(grammarAccess.getSitPropAccess().getGroup_1(), "rule__SitProp__Group_1__0");
			builder.put(grammarAccess.getSitPropAccess().getGroup_2(), "rule__SitProp__Group_2__0");
			builder.put(grammarAccess.getSitPropAccess().getGroup_3(), "rule__SitProp__Group_3__0");
			builder.put(grammarAccess.getEventPropAccess().getGroup_0(), "rule__EventProp__Group_0__0");
			builder.put(grammarAccess.getEventPropAccess().getGroup_1(), "rule__EventProp__Group_1__0");
			builder.put(grammarAccess.getEventPropAccess().getGroup_2(), "rule__EventProp__Group_2__0");
			builder.put(grammarAccess.getEventPropAccess().getGroup_3(), "rule__EventProp__Group_3__0");
			builder.put(grammarAccess.getIntervalAccess().getGroup_1(), "rule__Interval__Group_1__0");
			builder.put(grammarAccess.getIntervalAccess().getGroup_2(), "rule__Interval__Group_2__0");
			builder.put(grammarAccess.getIntervalAccess().getGroup_3(), "rule__Interval__Group_3__0");
			builder.put(grammarAccess.getIntervalAccess().getGroup_4(), "rule__Interval__Group_4__0");
			builder.put(grammarAccess.getIntConstAccess().getGroup(), "rule__IntConst__Group__0");
			builder.put(grammarAccess.getPointAccess().getGroup_1(), "rule__Point__Group_1__0");
			builder.put(grammarAccess.getPointAccess().getGroup_3(), "rule__Point__Group_3__0");
			builder.put(grammarAccess.getPointAccess().getGroup_4(), "rule__Point__Group_4__0");
			builder.put(grammarAccess.getPEventAccess().getGroup(), "rule__PEvent__Group__0");
			builder.put(grammarAccess.getCEventAccess().getGroup(), "rule__CEvent__Group__0");
			builder.put(grammarAccess.getOEventAccess().getGroup(), "rule__OEvent__Group__0");
			builder.put(grammarAccess.getPointConstAccess().getGroup(), "rule__PointConst__Group__0");
			builder.put(grammarAccess.getOStateAccess().getGroup(), "rule__OState__Group__0");
			builder.put(grammarAccess.getCStateAccess().getGroup(), "rule__CState__Group__0");
			builder.put(grammarAccess.getPowAccess().getGroup(), "rule__Pow__Group__0");
			builder.put(grammarAccess.getPowAccess().getGroup_2(), "rule__Pow__Group_2__0");
			builder.put(grammarAccess.getPStateAccess().getGroup(), "rule__PState__Group__0");
			builder.put(grammarAccess.getSetExpAccess().getGroup_0(), "rule__SetExp__Group_0__0");
			builder.put(grammarAccess.getSetExpAccess().getGroup_1(), "rule__SetExp__Group_1__0");
			builder.put(grammarAccess.getContractSpecAccess().getDomainSpecsAssignment_0(), "rule__ContractSpec__DomainSpecsAssignment_0");
			builder.put(grammarAccess.getContractSpecAccess().getContractsAssignment_1(), "rule__ContractSpec__ContractsAssignment_1");
			builder.put(grammarAccess.getDomainSpecAccess().getNameAssignment_1(), "rule__DomainSpec__NameAssignment_1");
			builder.put(grammarAccess.getDomainSpecAccess().getDConceptsAssignment_2_0(), "rule__DomainSpec__DConceptsAssignment_2_0");
			builder.put(grammarAccess.getDomainSpecAccess().getCtypesAssignment_3(), "rule__DomainSpec__CtypesAssignment_3");
			builder.put(grammarAccess.getDConceptAccess().getNameAssignment_0_0(), "rule__DConcept__NameAssignment_0_0");
			builder.put(grammarAccess.getDConceptAccess().getConceptTypesAssignment_0_1_1(), "rule__DConcept__ConceptTypesAssignment_0_1_1");
			builder.put(grammarAccess.getDConceptAccess().getAttributesAssignment_0_3_0(), "rule__DConcept__AttributesAssignment_0_3_0");
			builder.put(grammarAccess.getDConceptAccess().getAttributesAssignment_0_4(), "rule__DConcept__AttributesAssignment_0_4");
			builder.put(grammarAccess.getDConceptAccess().getNameAssignment_1_0(), "rule__DConcept__NameAssignment_1_0");
			builder.put(grammarAccess.getDConceptAccess().getEnumerationItemsAssignment_1_4_0(), "rule__DConcept__EnumerationItemsAssignment_1_4_0");
			builder.put(grammarAccess.getDConceptAccess().getEnumerationItemsAssignment_1_5(), "rule__DConcept__EnumerationItemsAssignment_1_5");
			builder.put(grammarAccess.getEnumItemAccess().getNameAssignment_1(), "rule__EnumItem__NameAssignment_1");
			builder.put(grammarAccess.getDomainTypeAccess().getDtypesAssignment(), "rule__DomainType__DtypesAssignment");
			builder.put(grammarAccess.getContractAccess().getNameAssignment_1(), "rule__Contract__NameAssignment_1");
			builder.put(grammarAccess.getContractAccess().getParametersAssignment_3_0(), "rule__Contract__ParametersAssignment_3_0");
			builder.put(grammarAccess.getContractAccess().getParametersAssignment_4(), "rule__Contract__ParametersAssignment_4");
			builder.put(grammarAccess.getContractAccess().getDeclarationsAssignment_6_1_0(), "rule__Contract__DeclarationsAssignment_6_1_0");
			builder.put(grammarAccess.getContractAccess().getPropositionsAssignment_7_1_0(), "rule__Contract__PropositionsAssignment_7_1_0");
			builder.put(grammarAccess.getContractAccess().getPropositionsAssignment_8_1_0(), "rule__Contract__PropositionsAssignment_8_1_0");
			builder.put(grammarAccess.getContractAccess().getObligationsAssignment_10_0(), "rule__Contract__ObligationsAssignment_10_0");
			builder.put(grammarAccess.getContractAccess().getObligationsAssignment_11_1_0(), "rule__Contract__ObligationsAssignment_11_1_0");
			builder.put(grammarAccess.getContractAccess().getPowersAssignment_12_1_0(), "rule__Contract__PowersAssignment_12_1_0");
			builder.put(grammarAccess.getContractAccess().getPropositionsAssignment_13_1_0(), "rule__Contract__PropositionsAssignment_13_1_0");
			builder.put(grammarAccess.getDeclarAccess().getNamesAssignment_2_0(), "rule__Declar__NamesAssignment_2_0");
			builder.put(grammarAccess.getDeclarAccess().getNamesAssignment_2_2(), "rule__Declar__NamesAssignment_2_2");
			builder.put(grammarAccess.getDeclarAccess().getNamesAssignment_3_0(), "rule__Declar__NamesAssignment_3_0");
			builder.put(grammarAccess.getDeclarAccess().getNamesAssignment_3_2(), "rule__Declar__NamesAssignment_3_2");
			builder.put(grammarAccess.getDeclarPairAccess().getNameAssignment_0(), "rule__DeclarPair__NameAssignment_0");
			builder.put(grammarAccess.getDeclarPairAccess().getTypeNamesAssignment_2(), "rule__DeclarPair__TypeNamesAssignment_2");
			builder.put(grammarAccess.getPairAccess().getNameAssignment_0(), "rule__Pair__NameAssignment_0");
			builder.put(grammarAccess.getPairAccess().getTypesAssignment_2(), "rule__Pair__TypesAssignment_2");
			builder.put(grammarAccess.getTypeNameAccess().getNameAssignment_0(), "rule__TypeName__NameAssignment_0");
			builder.put(grammarAccess.getOblAccess().getNameAssignment_0(), "rule__Obl__NameAssignment_0");
			builder.put(grammarAccess.getOblAccess().getTriggerAssignment_2_0(), "rule__Obl__TriggerAssignment_2_0");
			builder.put(grammarAccess.getOblAccess().getRolesAssignment_5(), "rule__Obl__RolesAssignment_5");
			builder.put(grammarAccess.getOblAccess().getRolesAssignment_7(), "rule__Obl__RolesAssignment_7");
			builder.put(grammarAccess.getOblAccess().getAntecedentAssignment_9(), "rule__Obl__AntecedentAssignment_9");
			builder.put(grammarAccess.getOblAccess().getConsequentAssignment_11(), "rule__Obl__ConsequentAssignment_11");
			builder.put(grammarAccess.getPropAccess().getJunctionsAssignment_0(), "rule__Prop__JunctionsAssignment_0");
			builder.put(grammarAccess.getPropAccess().getJunctionsAssignment_1_1(), "rule__Prop__JunctionsAssignment_1_1");
			builder.put(grammarAccess.getJuncAccess().getNegativeAtomsAssignment_0(), "rule__Junc__NegativeAtomsAssignment_0");
			builder.put(grammarAccess.getJuncAccess().getNegativeAtomsAssignment_1_1(), "rule__Junc__NegativeAtomsAssignment_1_1");
			builder.put(grammarAccess.getNegAccess().getAtomicExpressionsAssignment_1(), "rule__Neg__AtomicExpressionsAssignment_1");
			builder.put(grammarAccess.getAtomAccess().getEventPropositionsAssignment_0(), "rule__Atom__EventPropositionsAssignment_0");
			builder.put(grammarAccess.getAtomAccess().getSituationPropositionsAssignment_1(), "rule__Atom__SituationPropositionsAssignment_1");
			builder.put(grammarAccess.getAtomAccess().getShortHandNamesAssignment_2_0(), "rule__Atom__ShortHandNamesAssignment_2_0");
			builder.put(grammarAccess.getAtomAccess().getNamesAssignment_2_2_0(), "rule__Atom__NamesAssignment_2_2_0");
			builder.put(grammarAccess.getAtomAccess().getNamesAssignment_2_3(), "rule__Atom__NamesAssignment_2_3");
			builder.put(grammarAccess.getAtomAccess().getPointsAssignment_2_4_1(), "rule__Atom__PointsAssignment_2_4_1");
			builder.put(grammarAccess.getAtomAccess().getIntervalsAssignment_2_5_1(), "rule__Atom__IntervalsAssignment_2_5_1");
			builder.put(grammarAccess.getAtomAccess().getPointsAssignment_3_0(), "rule__Atom__PointsAssignment_3_0");
			builder.put(grammarAccess.getAtomAccess().getIntervalsAssignment_3_2(), "rule__Atom__IntervalsAssignment_3_2");
			builder.put(grammarAccess.getAtomAccess().getPropositionsAssignment_4_1(), "rule__Atom__PropositionsAssignment_4_1");
			builder.put(grammarAccess.getAtomAccess().getVarNameAssignment_5_1(), "rule__Atom__VarNameAssignment_5_1");
			builder.put(grammarAccess.getAtomAccess().getSetExpsAssignment_5_3(), "rule__Atom__SetExpsAssignment_5_3");
			builder.put(grammarAccess.getAtomAccess().getMetaconstraintsAssignment_5_5(), "rule__Atom__MetaconstraintsAssignment_5_5");
			builder.put(grammarAccess.getAtomAccess().getVarNameAssignment_6_1(), "rule__Atom__VarNameAssignment_6_1");
			builder.put(grammarAccess.getAtomAccess().getSetExpsAssignment_6_3(), "rule__Atom__SetExpsAssignment_6_3");
			builder.put(grammarAccess.getAtomAccess().getMetaconstraintsAssignment_6_5(), "rule__Atom__MetaconstraintsAssignment_6_5");
			builder.put(grammarAccess.getSitPropAccess().getSituationNameAssignment_0_2(), "rule__SitProp__SituationNameAssignment_0_2");
			builder.put(grammarAccess.getSitPropAccess().getIntervalsAssignment_0_4(), "rule__SitProp__IntervalsAssignment_0_4");
			builder.put(grammarAccess.getSitPropAccess().getOSituationNameAssignment_1_2(), "rule__SitProp__OSituationNameAssignment_1_2");
			builder.put(grammarAccess.getSitPropAccess().getIntervalsAssignment_1_4(), "rule__SitProp__IntervalsAssignment_1_4");
			builder.put(grammarAccess.getSitPropAccess().getCSituationNameAssignment_2_2(), "rule__SitProp__CSituationNameAssignment_2_2");
			builder.put(grammarAccess.getSitPropAccess().getIntervalsAssignment_2_4(), "rule__SitProp__IntervalsAssignment_2_4");
			builder.put(grammarAccess.getSitPropAccess().getPSituationNameAssignment_3_2(), "rule__SitProp__PSituationNameAssignment_3_2");
			builder.put(grammarAccess.getSitPropAccess().getIntervalsAssignment_3_4(), "rule__SitProp__IntervalsAssignment_3_4");
			builder.put(grammarAccess.getEventPropAccess().getEventNameAssignment_0_2(), "rule__EventProp__EventNameAssignment_0_2");
			builder.put(grammarAccess.getEventPropAccess().getPointsAssignment_0_4(), "rule__EventProp__PointsAssignment_0_4");
			builder.put(grammarAccess.getEventPropAccess().getOEventNameAssignment_1_2(), "rule__EventProp__OEventNameAssignment_1_2");
			builder.put(grammarAccess.getEventPropAccess().getPointsAssignment_1_4(), "rule__EventProp__PointsAssignment_1_4");
			builder.put(grammarAccess.getEventPropAccess().getCEventNameAssignment_2_2(), "rule__EventProp__CEventNameAssignment_2_2");
			builder.put(grammarAccess.getEventPropAccess().getPointsAssignment_2_4(), "rule__EventProp__PointsAssignment_2_4");
			builder.put(grammarAccess.getEventPropAccess().getPEventNameAssignment_3_2(), "rule__EventProp__PEventNameAssignment_3_2");
			builder.put(grammarAccess.getEventPropAccess().getPointsAssignment_3_4(), "rule__EventProp__PointsAssignment_3_4");
			builder.put(grammarAccess.getIntervalAccess().getSituationNameAssignment_0(), "rule__Interval__SituationNameAssignment_0");
			builder.put(grammarAccess.getIntervalAccess().getPointsAssignment_1_1(), "rule__Interval__PointsAssignment_1_1");
			builder.put(grammarAccess.getIntervalAccess().getPointsAssignment_1_3(), "rule__Interval__PointsAssignment_1_3");
			builder.put(grammarAccess.getIntervalAccess().getSituationNamesAssignment_3_0(), "rule__Interval__SituationNamesAssignment_3_0");
			builder.put(grammarAccess.getIntervalAccess().getTempOpsAssignment_3_1(), "rule__Interval__TempOpsAssignment_3_1");
			builder.put(grammarAccess.getIntervalAccess().getIntConstsAssignment_3_2(), "rule__Interval__IntConstsAssignment_3_2");
			builder.put(grammarAccess.getIntervalAccess().getUnitsAssignment_3_3(), "rule__Interval__UnitsAssignment_3_3");
			builder.put(grammarAccess.getIntervalAccess().getIntConstsAssignment_4_0(), "rule__Interval__IntConstsAssignment_4_0");
			builder.put(grammarAccess.getIntervalAccess().getUnitsAssignment_4_1(), "rule__Interval__UnitsAssignment_4_1");
			builder.put(grammarAccess.getIntervalAccess().getTempOpsAssignment_4_2(), "rule__Interval__TempOpsAssignment_4_2");
			builder.put(grammarAccess.getIntervalAccess().getSituationNamesAssignment_4_3(), "rule__Interval__SituationNamesAssignment_4_3");
			builder.put(grammarAccess.getSitNameAccess().getSitNameAssignment_0(), "rule__SitName__SitNameAssignment_0");
			builder.put(grammarAccess.getSitNameAccess().getOStatesAssignment_1(), "rule__SitName__OStatesAssignment_1");
			builder.put(grammarAccess.getSitNameAccess().getPStatesAssignment_2(), "rule__SitName__PStatesAssignment_2");
			builder.put(grammarAccess.getSitNameAccess().getCStatesAssignment_3(), "rule__SitName__CStatesAssignment_3");
			builder.put(grammarAccess.getSitNameAccess().getOEventsAssignment_4(), "rule__SitName__OEventsAssignment_4");
			builder.put(grammarAccess.getSitNameAccess().getCEventsAssignment_5(), "rule__SitName__CEventsAssignment_5");
			builder.put(grammarAccess.getSitNameAccess().getPEventsAssignment_6(), "rule__SitName__PEventsAssignment_6");
			builder.put(grammarAccess.getIntConstAccess().getTypeAssignment_1(), "rule__IntConst__TypeAssignment_1");
			builder.put(grammarAccess.getPointAccess().getEventNamesAssignment_0(), "rule__Point__EventNamesAssignment_0");
			builder.put(grammarAccess.getPointAccess().getPointConstsAssignment_2(), "rule__Point__PointConstsAssignment_2");
			builder.put(grammarAccess.getPointAccess().getPointConstsAssignment_3_0(), "rule__Point__PointConstsAssignment_3_0");
			builder.put(grammarAccess.getPointAccess().getUnitsAssignment_3_1(), "rule__Point__UnitsAssignment_3_1");
			builder.put(grammarAccess.getPointAccess().getTempOpsAssignment_3_2(), "rule__Point__TempOpsAssignment_3_2");
			builder.put(grammarAccess.getPointAccess().getEventNamesAssignment_3_3(), "rule__Point__EventNamesAssignment_3_3");
			builder.put(grammarAccess.getPointAccess().getEventNamesAssignment_4_0(), "rule__Point__EventNamesAssignment_4_0");
			builder.put(grammarAccess.getPointAccess().getTempOpsAssignment_4_1(), "rule__Point__TempOpsAssignment_4_1");
			builder.put(grammarAccess.getPointAccess().getPointConstsAssignment_4_2(), "rule__Point__PointConstsAssignment_4_2");
			builder.put(grammarAccess.getPointAccess().getUnitsAssignment_4_3(), "rule__Point__UnitsAssignment_4_3");
			builder.put(grammarAccess.getNameAccess().getNameAssignment(), "rule__Name__NameAssignment");
			builder.put(grammarAccess.getPEventAccess().getPowEventAssignment_0(), "rule__PEvent__PowEventAssignment_0");
			builder.put(grammarAccess.getPEventAccess().getPowNameAssignment_2(), "rule__PEvent__PowNameAssignment_2");
			builder.put(grammarAccess.getCEventAccess().getContrEventAssignment_0(), "rule__CEvent__ContrEventAssignment_0");
			builder.put(grammarAccess.getCEventAccess().getContrNameAssignment_2(), "rule__CEvent__ContrNameAssignment_2");
			builder.put(grammarAccess.getOEventAccess().getOblEventAssignment_0(), "rule__OEvent__OblEventAssignment_0");
			builder.put(grammarAccess.getOEventAccess().getOblNameAssignment_2(), "rule__OEvent__OblNameAssignment_2");
			builder.put(grammarAccess.getPointConstAccess().getTypeAssignment_1(), "rule__PointConst__TypeAssignment_1");
			builder.put(grammarAccess.getOStateAccess().getOblStateAssignment_0(), "rule__OState__OblStateAssignment_0");
			builder.put(grammarAccess.getOStateAccess().getOblNameAssignment_2(), "rule__OState__OblNameAssignment_2");
			builder.put(grammarAccess.getCStateAccess().getContrStateAssignment_0(), "rule__CState__ContrStateAssignment_0");
			builder.put(grammarAccess.getCStateAccess().getContractNameAssignment_2(), "rule__CState__ContractNameAssignment_2");
			builder.put(grammarAccess.getPowAccess().getNameAssignment_0(), "rule__Pow__NameAssignment_0");
			builder.put(grammarAccess.getPowAccess().getTriggerAssignment_2_0(), "rule__Pow__TriggerAssignment_2_0");
			builder.put(grammarAccess.getPowAccess().getRolesAssignment_5(), "rule__Pow__RolesAssignment_5");
			builder.put(grammarAccess.getPowAccess().getRolesAssignment_7(), "rule__Pow__RolesAssignment_7");
			builder.put(grammarAccess.getPowAccess().getAntecedentsAssignment_9(), "rule__Pow__AntecedentsAssignment_9");
			builder.put(grammarAccess.getPowAccess().getConsequentsAssignment_11(), "rule__Pow__ConsequentsAssignment_11");
			builder.put(grammarAccess.getPStateAccess().getPowStateAssignment_0(), "rule__PState__PowStateAssignment_0");
			builder.put(grammarAccess.getPStateAccess().getPowNameAssignment_2(), "rule__PState__PowNameAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SymboleociGrammarAccess grammarAccess;

	@Override
	protected InternalSymboleociParser createParser() {
		InternalSymboleociParser result = new InternalSymboleociParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SymboleociGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SymboleociGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
