/*
 * generated by Xtext 2.22.0
 */
package symboleoci;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SymboleociStandaloneSetup extends SymboleociStandaloneSetupGenerated {

	public static void doSetup() {
		new SymboleociStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
