/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declar Pair</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.DeclarPair#getNames <em>Names</em>}</li>
 *   <li>{@link symboleoci.symboleoci.DeclarPair#getName <em>Name</em>}</li>
 *   <li>{@link symboleoci.symboleoci.DeclarPair#getTypeNames <em>Type Names</em>}</li>
 * </ul>
 *
 * @see symboleoci.symboleoci.SymboleociPackage#getDeclarPair()
 * @model
 * @generated
 */
public interface DeclarPair extends Param, Declar
{
  /**
   * Returns the value of the '<em><b>Names</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.Name}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Names</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getDeclarPair_Names()
   * @model containment="true"
   * @generated
   */
  EList<Name> getNames();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see symboleoci.symboleoci.SymboleociPackage#getDeclarPair_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.DeclarPair#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type Names</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.TypeName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Names</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getDeclarPair_TypeNames()
   * @model containment="true"
   * @generated
   */
  EList<TypeName> getTypeNames();

} // DeclarPair
