/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Prop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.EventProp#getEventName <em>Event Name</em>}</li>
 *   <li>{@link symboleoci.symboleoci.EventProp#getPoints <em>Points</em>}</li>
 *   <li>{@link symboleoci.symboleoci.EventProp#getOEventName <em>OEvent Name</em>}</li>
 *   <li>{@link symboleoci.symboleoci.EventProp#getCEventName <em>CEvent Name</em>}</li>
 *   <li>{@link symboleoci.symboleoci.EventProp#getPEventName <em>PEvent Name</em>}</li>
 * </ul>
 *
 * @see symboleoci.symboleoci.SymboleociPackage#getEventProp()
 * @model
 * @generated
 */
public interface EventProp extends EObject
{
  /**
   * Returns the value of the '<em><b>Event Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Name</em>' reference.
   * @see #setEventName(Declar)
   * @see symboleoci.symboleoci.SymboleociPackage#getEventProp_EventName()
   * @model
   * @generated
   */
  Declar getEventName();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.EventProp#getEventName <em>Event Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Name</em>' reference.
   * @see #getEventName()
   * @generated
   */
  void setEventName(Declar value);

  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.Point}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getEventProp_Points()
   * @model containment="true"
   * @generated
   */
  EList<Point> getPoints();

  /**
   * Returns the value of the '<em><b>OEvent Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>OEvent Name</em>' containment reference.
   * @see #setOEventName(oEvent)
   * @see symboleoci.symboleoci.SymboleociPackage#getEventProp_OEventName()
   * @model containment="true"
   * @generated
   */
  oEvent getOEventName();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.EventProp#getOEventName <em>OEvent Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>OEvent Name</em>' containment reference.
   * @see #getOEventName()
   * @generated
   */
  void setOEventName(oEvent value);

  /**
   * Returns the value of the '<em><b>CEvent Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CEvent Name</em>' containment reference.
   * @see #setCEventName(cEvent)
   * @see symboleoci.symboleoci.SymboleociPackage#getEventProp_CEventName()
   * @model containment="true"
   * @generated
   */
  cEvent getCEventName();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.EventProp#getCEventName <em>CEvent Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>CEvent Name</em>' containment reference.
   * @see #getCEventName()
   * @generated
   */
  void setCEventName(cEvent value);

  /**
   * Returns the value of the '<em><b>PEvent Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PEvent Name</em>' containment reference.
   * @see #setPEventName(pEvent)
   * @see symboleoci.symboleoci.SymboleociPackage#getEventProp_PEventName()
   * @model containment="true"
   * @generated
   */
  pEvent getPEventName();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.EventProp#getPEventName <em>PEvent Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PEvent Name</em>' containment reference.
   * @see #getPEventName()
   * @generated
   */
  void setPEventName(pEvent value);

} // EventProp
