/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Const</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.IntConst#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see symboleoci.symboleoci.SymboleociPackage#getIntConst()
 * @model
 * @generated
 */
public interface IntConst extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(int)
   * @see symboleoci.symboleoci.SymboleociPackage#getIntConst_Type()
   * @model
   * @generated
   */
  int getType();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.IntConst#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(int value);

} // IntConst
