/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pair</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.Pair#getName <em>Name</em>}</li>
 *   <li>{@link symboleoci.symboleoci.Pair#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @see symboleoci.symboleoci.SymboleociPackage#getPair()
 * @model
 * @generated
 */
public interface Pair extends Att
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see symboleoci.symboleoci.SymboleociPackage#getPair_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.Pair#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.CType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getPair_Types()
   * @model containment="true"
   * @generated
   */
  EList<CType> getTypes();

} // Pair
