/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>cState</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.cState#getContrState <em>Contr State</em>}</li>
 *   <li>{@link symboleoci.symboleoci.cState#getContractName <em>Contract Name</em>}</li>
 * </ul>
 *
 * @see symboleoci.symboleoci.SymboleociPackage#getcState()
 * @model
 * @generated
 */
public interface cState extends EObject
{
  /**
   * Returns the value of the '<em><b>Contr State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contr State</em>' attribute.
   * @see #setContrState(String)
   * @see symboleoci.symboleoci.SymboleociPackage#getcState_ContrState()
   * @model
   * @generated
   */
  String getContrState();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.cState#getContrState <em>Contr State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contr State</em>' attribute.
   * @see #getContrState()
   * @generated
   */
  void setContrState(String value);

  /**
   * Returns the value of the '<em><b>Contract Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contract Name</em>' reference.
   * @see #setContractName(Contract)
   * @see symboleoci.symboleoci.SymboleociPackage#getcState_ContractName()
   * @model
   * @generated
   */
  Contract getContractName();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.cState#getContractName <em>Contract Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contract Name</em>' reference.
   * @see #getContractName()
   * @generated
   */
  void setContractName(Contract value);

} // cState
