/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DConcept</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.DConcept#getName <em>Name</em>}</li>
 *   <li>{@link symboleoci.symboleoci.DConcept#getConceptTypes <em>Concept Types</em>}</li>
 *   <li>{@link symboleoci.symboleoci.DConcept#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link symboleoci.symboleoci.DConcept#getEnumerationItems <em>Enumeration Items</em>}</li>
 * </ul>
 *
 * @see symboleoci.symboleoci.SymboleociPackage#getDConcept()
 * @model
 * @generated
 */
public interface DConcept extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see symboleoci.symboleoci.SymboleociPackage#getDConcept_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link symboleoci.symboleoci.DConcept#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Concept Types</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.CType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concept Types</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getDConcept_ConceptTypes()
   * @model containment="true"
   * @generated
   */
  EList<CType> getConceptTypes();

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.Att}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getDConcept_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Att> getAttributes();

  /**
   * Returns the value of the '<em><b>Enumeration Items</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.enumItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumeration Items</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getDConcept_EnumerationItems()
   * @model containment="true"
   * @generated
   */
  EList<enumItem> getEnumerationItems();

} // DConcept
