/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Junc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.Junc#getNegativeAtoms <em>Negative Atoms</em>}</li>
 * </ul>
 *
 * @see symboleoci.symboleoci.SymboleociPackage#getJunc()
 * @model
 * @generated
 */
public interface Junc extends EObject
{
  /**
   * Returns the value of the '<em><b>Negative Atoms</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.Neg}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negative Atoms</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getJunc_NegativeAtoms()
   * @model containment="true"
   * @generated
   */
  EList<Neg> getNegativeAtoms();

} // Junc
