/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.Point#getEventNames <em>Event Names</em>}</li>
 *   <li>{@link symboleoci.symboleoci.Point#getPointConsts <em>Point Consts</em>}</li>
 *   <li>{@link symboleoci.symboleoci.Point#getUnits <em>Units</em>}</li>
 *   <li>{@link symboleoci.symboleoci.Point#getTempOps <em>Temp Ops</em>}</li>
 * </ul>
 *
 * @see symboleoci.symboleoci.SymboleociPackage#getPoint()
 * @model
 * @generated
 */
public interface Point extends EObject
{
  /**
   * Returns the value of the '<em><b>Event Names</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.SitName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Names</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getPoint_EventNames()
   * @model containment="true"
   * @generated
   */
  EList<SitName> getEventNames();

  /**
   * Returns the value of the '<em><b>Point Consts</b></em>' containment reference list.
   * The list contents are of type {@link symboleoci.symboleoci.PointConst}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point Consts</em>' containment reference list.
   * @see symboleoci.symboleoci.SymboleociPackage#getPoint_PointConsts()
   * @model containment="true"
   * @generated
   */
  EList<PointConst> getPointConsts();

  /**
   * Returns the value of the '<em><b>Units</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units</em>' attribute list.
   * @see symboleoci.symboleoci.SymboleociPackage#getPoint_Units()
   * @model unique="false"
   * @generated
   */
  EList<String> getUnits();

  /**
   * Returns the value of the '<em><b>Temp Ops</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp Ops</em>' attribute list.
   * @see symboleoci.symboleoci.SymboleociPackage#getPoint_TempOps()
   * @model unique="false"
   * @generated
   */
  EList<String> getTempOps();

} // Point
