/*
 * generated by Xtext 2.22.0
 */
package symboleoci.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSymboleociScopeProvider extends DelegatingScopeProvider {
}
