/*
 * generated by Xtext 2.22.0
 */
package symboleoci.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import symboleoci.parser.antlr.internal.InternalSymboleociParser;
import symboleoci.services.SymboleociGrammarAccess;

public class SymboleociParser extends AbstractAntlrParser {

	@Inject
	private SymboleociGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSymboleociParser createParser(XtextTokenStream stream) {
		return new InternalSymboleociParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ContractSpec";
	}

	public SymboleociGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SymboleociGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
