/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoide.symboleoide.Atom#getEventPropositions <em>Event Propositions</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getSituationPropositions <em>Situation Propositions</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getShortHandNames <em>Short Hand Names</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getNames <em>Names</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getPoints <em>Points</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getIntervals <em>Intervals</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getPropositions <em>Propositions</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getVarName <em>Var Name</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getSetExps <em>Set Exps</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Atom#getMetaconstraints <em>Metaconstraints</em>}</li>
 * </ul>
 *
 * @see symboleoide.symboleoide.SymboleoidePackage#getAtom()
 * @model
 * @generated
 */
public interface Atom extends EObject
{
  /**
   * Returns the value of the '<em><b>Event Propositions</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.EventProp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Propositions</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_EventPropositions()
   * @model containment="true"
   * @generated
   */
  EList<EventProp> getEventPropositions();

  /**
   * Returns the value of the '<em><b>Situation Propositions</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.SitProp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Situation Propositions</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_SituationPropositions()
   * @model containment="true"
   * @generated
   */
  EList<SitProp> getSituationPropositions();

  /**
   * Returns the value of the '<em><b>Short Hand Names</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Name}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Short Hand Names</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_ShortHandNames()
   * @model containment="true"
   * @generated
   */
  EList<Name> getShortHandNames();

  /**
   * Returns the value of the '<em><b>Names</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Name}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Names</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_Names()
   * @model containment="true"
   * @generated
   */
  EList<Name> getNames();

  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Point}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_Points()
   * @model containment="true"
   * @generated
   */
  EList<Point> getPoints();

  /**
   * Returns the value of the '<em><b>Intervals</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Interval}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intervals</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_Intervals()
   * @model containment="true"
   * @generated
   */
  EList<Interval> getIntervals();

  /**
   * Returns the value of the '<em><b>Propositions</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Prop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Propositions</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_Propositions()
   * @model containment="true"
   * @generated
   */
  EList<Prop> getPropositions();

  /**
   * Returns the value of the '<em><b>Var Name</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Name}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_VarName()
   * @model containment="true"
   * @generated
   */
  EList<Name> getVarName();

  /**
   * Returns the value of the '<em><b>Set Exps</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set Exps</em>' attribute list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_SetExps()
   * @model unique="false"
   * @generated
   */
  EList<String> getSetExps();

  /**
   * Returns the value of the '<em><b>Metaconstraints</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metaconstraints</em>' attribute list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getAtom_Metaconstraints()
   * @model unique="false"
   * @generated
   */
  EList<String> getMetaconstraints();

} // Atom
