/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Att</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see symboleoide.symboleoide.SymboleoidePackage#getAtt()
 * @model
 * @generated
 */
public interface Att extends EObject
{
} // Att
