/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoide.symboleoide.ContractSpec#getDomainSpecs <em>Domain Specs</em>}</li>
 *   <li>{@link symboleoide.symboleoide.ContractSpec#getContracts <em>Contracts</em>}</li>
 * </ul>
 *
 * @see symboleoide.symboleoide.SymboleoidePackage#getContractSpec()
 * @model
 * @generated
 */
public interface ContractSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Domain Specs</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.DomainSpec}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain Specs</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getContractSpec_DomainSpecs()
   * @model containment="true"
   * @generated
   */
  EList<DomainSpec> getDomainSpecs();

  /**
   * Returns the value of the '<em><b>Contracts</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Contract}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contracts</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getContractSpec_Contracts()
   * @model containment="true"
   * @generated
   */
  EList<Contract> getContracts();

} // ContractSpec
