/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoide.symboleoide.Contract#getName <em>Name</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Contract#getParameters <em>Parameters</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Contract#getDeclarations <em>Declarations</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Contract#getPropositions <em>Propositions</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Contract#getObligations <em>Obligations</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Contract#getPowers <em>Powers</em>}</li>
 * </ul>
 *
 * @see symboleoide.symboleoide.SymboleoidePackage#getContract()
 * @model
 * @generated
 */
public interface Contract extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see symboleoide.symboleoide.SymboleoidePackage#getContract_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link symboleoide.symboleoide.Contract#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Param}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getContract_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Param> getParameters();

  /**
   * Returns the value of the '<em><b>Declarations</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Declar}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarations</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getContract_Declarations()
   * @model containment="true"
   * @generated
   */
  EList<Declar> getDeclarations();

  /**
   * Returns the value of the '<em><b>Propositions</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Prop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Propositions</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getContract_Propositions()
   * @model containment="true"
   * @generated
   */
  EList<Prop> getPropositions();

  /**
   * Returns the value of the '<em><b>Obligations</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Obl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligations</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getContract_Obligations()
   * @model containment="true"
   * @generated
   */
  EList<Obl> getObligations();

  /**
   * Returns the value of the '<em><b>Powers</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Pow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Powers</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getContract_Powers()
   * @model containment="true"
   * @generated
   */
  EList<Pow> getPowers();

} // Contract
