/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoide.symboleoide.Obl#getName <em>Name</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Obl#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Obl#getRoles <em>Roles</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Obl#getAntecedent <em>Antecedent</em>}</li>
 *   <li>{@link symboleoide.symboleoide.Obl#getConsequent <em>Consequent</em>}</li>
 * </ul>
 *
 * @see symboleoide.symboleoide.SymboleoidePackage#getObl()
 * @model
 * @generated
 */
public interface Obl extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see symboleoide.symboleoide.SymboleoidePackage#getObl_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link symboleoide.symboleoide.Obl#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Trigger</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' containment reference.
   * @see #setTrigger(Prop)
   * @see symboleoide.symboleoide.SymboleoidePackage#getObl_Trigger()
   * @model containment="true"
   * @generated
   */
  Prop getTrigger();

  /**
   * Sets the value of the '{@link symboleoide.symboleoide.Obl#getTrigger <em>Trigger</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' containment reference.
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(Prop value);

  /**
   * Returns the value of the '<em><b>Roles</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Name}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roles</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getObl_Roles()
   * @model containment="true"
   * @generated
   */
  EList<Name> getRoles();

  /**
   * Returns the value of the '<em><b>Antecedent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Antecedent</em>' containment reference.
   * @see #setAntecedent(Prop)
   * @see symboleoide.symboleoide.SymboleoidePackage#getObl_Antecedent()
   * @model containment="true"
   * @generated
   */
  Prop getAntecedent();

  /**
   * Sets the value of the '{@link symboleoide.symboleoide.Obl#getAntecedent <em>Antecedent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Antecedent</em>' containment reference.
   * @see #getAntecedent()
   * @generated
   */
  void setAntecedent(Prop value);

  /**
   * Returns the value of the '<em><b>Consequent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consequent</em>' containment reference.
   * @see #setConsequent(Prop)
   * @see symboleoide.symboleoide.SymboleoidePackage#getObl_Consequent()
   * @model containment="true"
   * @generated
   */
  Prop getConsequent();

  /**
   * Sets the value of the '{@link symboleoide.symboleoide.Obl#getConsequent <em>Consequent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consequent</em>' containment reference.
   * @see #getConsequent()
   * @generated
   */
  void setConsequent(Prop value);

} // Obl
