/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>oState</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoide.symboleoide.oState#getOblState <em>Obl State</em>}</li>
 *   <li>{@link symboleoide.symboleoide.oState#getOblName <em>Obl Name</em>}</li>
 * </ul>
 *
 * @see symboleoide.symboleoide.SymboleoidePackage#getoState()
 * @model
 * @generated
 */
public interface oState extends EObject
{
  /**
   * Returns the value of the '<em><b>Obl State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obl State</em>' attribute.
   * @see #setOblState(String)
   * @see symboleoide.symboleoide.SymboleoidePackage#getoState_OblState()
   * @model
   * @generated
   */
  String getOblState();

  /**
   * Sets the value of the '{@link symboleoide.symboleoide.oState#getOblState <em>Obl State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obl State</em>' attribute.
   * @see #getOblState()
   * @generated
   */
  void setOblState(String value);

  /**
   * Returns the value of the '<em><b>Obl Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obl Name</em>' reference.
   * @see #setOblName(Obl)
   * @see symboleoide.symboleoide.SymboleoidePackage#getoState_OblName()
   * @model
   * @generated
   */
  Obl getOblName();

  /**
   * Sets the value of the '{@link symboleoide.symboleoide.oState#getOblName <em>Obl Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obl Name</em>' reference.
   * @see #getOblName()
   * @generated
   */
  void setOblName(Obl value);

} // oState
