/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoide.symboleoide.Prop#getJunctions <em>Junctions</em>}</li>
 * </ul>
 *
 * @see symboleoide.symboleoide.SymboleoidePackage#getProp()
 * @model
 * @generated
 */
public interface Prop extends EObject
{
  /**
   * Returns the value of the '<em><b>Junctions</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Junc}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Junctions</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getProp_Junctions()
   * @model containment="true"
   * @generated
   */
  EList<Junc> getJunctions();

} // Prop
