/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sit Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link symboleoide.symboleoide.SitName#getSitName <em>Sit Name</em>}</li>
 *   <li>{@link symboleoide.symboleoide.SitName#getOStates <em>OStates</em>}</li>
 *   <li>{@link symboleoide.symboleoide.SitName#getPStates <em>PStates</em>}</li>
 *   <li>{@link symboleoide.symboleoide.SitName#getCStates <em>CStates</em>}</li>
 *   <li>{@link symboleoide.symboleoide.SitName#getOEvents <em>OEvents</em>}</li>
 *   <li>{@link symboleoide.symboleoide.SitName#getCEvents <em>CEvents</em>}</li>
 *   <li>{@link symboleoide.symboleoide.SitName#getPEvents <em>PEvents</em>}</li>
 * </ul>
 *
 * @see symboleoide.symboleoide.SymboleoidePackage#getSitName()
 * @model
 * @generated
 */
public interface SitName extends EObject
{
  /**
   * Returns the value of the '<em><b>Sit Name</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.Name}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sit Name</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getSitName_SitName()
   * @model containment="true"
   * @generated
   */
  EList<Name> getSitName();

  /**
   * Returns the value of the '<em><b>OStates</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.oState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>OStates</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getSitName_OStates()
   * @model containment="true"
   * @generated
   */
  EList<oState> getOStates();

  /**
   * Returns the value of the '<em><b>PStates</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.pState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PStates</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getSitName_PStates()
   * @model containment="true"
   * @generated
   */
  EList<pState> getPStates();

  /**
   * Returns the value of the '<em><b>CStates</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.cState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CStates</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getSitName_CStates()
   * @model containment="true"
   * @generated
   */
  EList<cState> getCStates();

  /**
   * Returns the value of the '<em><b>OEvents</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.oEvent}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>OEvents</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getSitName_OEvents()
   * @model containment="true"
   * @generated
   */
  EList<oEvent> getOEvents();

  /**
   * Returns the value of the '<em><b>CEvents</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.cEvent}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CEvents</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getSitName_CEvents()
   * @model containment="true"
   * @generated
   */
  EList<cEvent> getCEvents();

  /**
   * Returns the value of the '<em><b>PEvents</b></em>' containment reference list.
   * The list contents are of type {@link symboleoide.symboleoide.pEvent}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PEvents</em>' containment reference list.
   * @see symboleoide.symboleoide.SymboleoidePackage#getSitName_PEvents()
   * @model containment="true"
   * @generated
   */
  EList<pEvent> getPEvents();

} // SitName
