/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import symboleoide.symboleoide.Declar;
import symboleoide.symboleoide.SymboleoidePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Declar</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DeclarImpl extends MinimalEObjectImpl.Container implements Declar
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclarImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoidePackage.Literals.DECLAR;
  }

} //DeclarImpl
