/**
 * generated by Xtext 2.22.0
 */
package symboleoide.symboleoide.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import symboleoide.symboleoide.Pow;
import symboleoide.symboleoide.SymboleoidePackage;
import symboleoide.symboleoide.pState;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>pState</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link symboleoide.symboleoide.impl.pStateImpl#getPowState <em>Pow State</em>}</li>
 *   <li>{@link symboleoide.symboleoide.impl.pStateImpl#getPowName <em>Pow Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class pStateImpl extends MinimalEObjectImpl.Container implements pState
{
  /**
   * The default value of the '{@link #getPowState() <em>Pow State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowState()
   * @generated
   * @ordered
   */
  protected static final String POW_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPowState() <em>Pow State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowState()
   * @generated
   * @ordered
   */
  protected String powState = POW_STATE_EDEFAULT;

  /**
   * The cached value of the '{@link #getPowName() <em>Pow Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowName()
   * @generated
   * @ordered
   */
  protected Pow powName;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected pStateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoidePackage.Literals.PSTATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPowState()
  {
    return powState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPowState(String newPowState)
  {
    String oldPowState = powState;
    powState = newPowState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoidePackage.PSTATE__POW_STATE, oldPowState, powState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Pow getPowName()
  {
    if (powName != null && powName.eIsProxy())
    {
      InternalEObject oldPowName = (InternalEObject)powName;
      powName = (Pow)eResolveProxy(oldPowName);
      if (powName != oldPowName)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SymboleoidePackage.PSTATE__POW_NAME, oldPowName, powName));
      }
    }
    return powName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Pow basicGetPowName()
  {
    return powName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPowName(Pow newPowName)
  {
    Pow oldPowName = powName;
    powName = newPowName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoidePackage.PSTATE__POW_NAME, oldPowName, powName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoidePackage.PSTATE__POW_STATE:
        return getPowState();
      case SymboleoidePackage.PSTATE__POW_NAME:
        if (resolve) return getPowName();
        return basicGetPowName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoidePackage.PSTATE__POW_STATE:
        setPowState((String)newValue);
        return;
      case SymboleoidePackage.PSTATE__POW_NAME:
        setPowName((Pow)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoidePackage.PSTATE__POW_STATE:
        setPowState(POW_STATE_EDEFAULT);
        return;
      case SymboleoidePackage.PSTATE__POW_NAME:
        setPowName((Pow)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoidePackage.PSTATE__POW_STATE:
        return POW_STATE_EDEFAULT == null ? powState != null : !POW_STATE_EDEFAULT.equals(powState);
      case SymboleoidePackage.PSTATE__POW_NAME:
        return powName != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (powState: ");
    result.append(powState);
    result.append(')');
    return result.toString();
  }

} //pStateImpl
