/*
 * generated by Xtext 2.22.0
 */
package symboleoci.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import symboleoci.SymboleociRuntimeModule;
import symboleoci.SymboleociStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SymboleociIdeSetup extends SymboleociStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SymboleociRuntimeModule(), new SymboleociIdeModule()));
	}
	
}
