/*
 * generated by Xtext 2.22.0
 */
package symboleoci.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSymboleociValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(symboleoci.symboleoci.SymboleociPackage.eINSTANCE);
		return result;
	}
}
