/**
 * generated by Xtext 2.22.0
 */
package symboleoci.symboleoci.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import symboleoci.symboleoci.Contract;
import symboleoci.symboleoci.SymboleociPackage;
import symboleoci.symboleoci.cEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>cEvent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link symboleoci.symboleoci.impl.cEventImpl#getContrEvent <em>Contr Event</em>}</li>
 *   <li>{@link symboleoci.symboleoci.impl.cEventImpl#getContrName <em>Contr Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class cEventImpl extends MinimalEObjectImpl.Container implements cEvent
{
  /**
   * The default value of the '{@link #getContrEvent() <em>Contr Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrEvent()
   * @generated
   * @ordered
   */
  protected static final String CONTR_EVENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContrEvent() <em>Contr Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrEvent()
   * @generated
   * @ordered
   */
  protected String contrEvent = CONTR_EVENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getContrName() <em>Contr Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrName()
   * @generated
   * @ordered
   */
  protected Contract contrName;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected cEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleociPackage.Literals.CEVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getContrEvent()
  {
    return contrEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContrEvent(String newContrEvent)
  {
    String oldContrEvent = contrEvent;
    contrEvent = newContrEvent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleociPackage.CEVENT__CONTR_EVENT, oldContrEvent, contrEvent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Contract getContrName()
  {
    if (contrName != null && contrName.eIsProxy())
    {
      InternalEObject oldContrName = (InternalEObject)contrName;
      contrName = (Contract)eResolveProxy(oldContrName);
      if (contrName != oldContrName)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SymboleociPackage.CEVENT__CONTR_NAME, oldContrName, contrName));
      }
    }
    return contrName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Contract basicGetContrName()
  {
    return contrName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContrName(Contract newContrName)
  {
    Contract oldContrName = contrName;
    contrName = newContrName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleociPackage.CEVENT__CONTR_NAME, oldContrName, contrName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleociPackage.CEVENT__CONTR_EVENT:
        return getContrEvent();
      case SymboleociPackage.CEVENT__CONTR_NAME:
        if (resolve) return getContrName();
        return basicGetContrName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleociPackage.CEVENT__CONTR_EVENT:
        setContrEvent((String)newValue);
        return;
      case SymboleociPackage.CEVENT__CONTR_NAME:
        setContrName((Contract)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleociPackage.CEVENT__CONTR_EVENT:
        setContrEvent(CONTR_EVENT_EDEFAULT);
        return;
      case SymboleociPackage.CEVENT__CONTR_NAME:
        setContrName((Contract)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleociPackage.CEVENT__CONTR_EVENT:
        return CONTR_EVENT_EDEFAULT == null ? contrEvent != null : !CONTR_EVENT_EDEFAULT.equals(contrEvent);
      case SymboleociPackage.CEVENT__CONTR_NAME:
        return contrName != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (contrEvent: ");
    result.append(contrEvent);
    result.append(')');
    return result.toString();
  }

} //cEventImpl
