/*
 * generated by Xtext 2.22.0
 */
package symboleoci.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SymboleociAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("symboleoci/parser/antlr/internal/InternalSymboleoci.tokens");
	}
}
