/*
 * generated by Xtext 2.22.0
 */
package symboleoide.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import symboleoide.parser.antlr.internal.InternalSymboleoideParser;
import symboleoide.services.SymboleoideGrammarAccess;

public class SymboleoideParser extends AbstractAntlrParser {

	@Inject
	private SymboleoideGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSymboleoideParser createParser(XtextTokenStream stream) {
		return new InternalSymboleoideParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ContractSpec";
	}

	public SymboleoideGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SymboleoideGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
